aurum/aurum/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("shop.urls")),
    path('user/',include("user.urls"))
]

aurum/shop/urls.py
from django.urls import path , re_path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [
    path('' , views.index , name="index"),
    path('about/' , views.about , name="about"),
    path('cart/' , views.cart , name="cart"),
    path('del_cart_item/' , views.del_cart_item , name="delcartitem"),
    path('calcu_cart_item/' , views.calcu_cart_item , name="calcucartitem"),
    path('catalog/' , views.ProductListView.as_view(), name="catalog"),
    path('payment/' , views.payment, name="payment"),
    path('factor/' , views.factor, name="factor"),
    path('like_dislike/' , views.like_dislike, name="like_dislike"),
    re_path(r'^detail/(?P<pk>\d+)/$',views.ProductDetailView.as_view(), name='ProductDetail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aurum/user/urls.py
from django.urls import path , re_path
from user import views as user_views
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    path('register/' , user_views.register , name='register'),
    path('profile/' , user_views.profile , name='profile'), 
    path('login/' , auth_views.LoginView.as_view(template_name='user/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

aurum/media/templates/partials/footer.html
<footer class="footer">
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col-sm-6 col-md-3 pt-2">
                <h5>Women's</h5>
                <ul class="nav-footer">
                    {% for w in women %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' w.pk %}">{{w.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-6 col-md-3 pt-2">
                <h5>Men's</h5>
                <ul class="nav-footer">
                    {% for m in men %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' m.pk %}">{{m.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-6 col-md-3 pt-2">
                <h5>Girl's</h5>
                <ul class="nav-footer">
                    {% for g in girls %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' g.pk %}">{{g.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-sm-6 col-md-3 pt-2">
                <h5>Boy's</h5>
                <ul class="nav-footer">
                    {% for b in boys %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' b.pk %}">{{b.name}}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="divider"></div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6 text-center text-md-left mt-2 mb-3 pt-1">
                <p class="copyright">Copyright &copy; Example. Theme by <a href="https://medialoot.com">Medialoot</a>.
                </p>
            </div>
            <div class="col-md-6 text-center text-md-right mb-4">
                <ul class="social">
                    <li><a href="{{ aboutus_G.facebook }}"  target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
                    <li><a href="{{ aboutus_G.twitter }}"   target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="{{ aboutus_G.telegram }}"  target="_blank" title="Telegram"><i class="fab fa-telegram"></i></a></li>
                    <li><a href="{{ aboutus_G.instagram }}" target="_blank" title="Instagram"><i class="fab fa-instagram"></i></a></li>
                    <div class="clear"></div>
                </ul>
            </div>
        </div>
    </div>
</footer>

aurum/media/templates/partials/header.html
<section class="header text-center">
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom">
        <div class="container"><a class="navbar-brand" href="{% url 'shop:index' %}"><i
                    class="fas fa-shopping-bag primary-color mr-1"></i> Aurum</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-1"
                aria-controls="navbar-1" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse pull-xs-right justify-content-end" id="navbar-1">
                <ul class="navbar-nav mt-2 mt-md-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:index' %}">Home <span
                                class="sr-only">(current)</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:catalog' %}">catalog</a></li>
                    <li class="nav-item dropdown mega-menu"><a class="nav-link dropdown-toggle" href="{% url 'shop:catalog' %}"
                            id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">Shop </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <div class="container">
                                <div class="divider"></div>
                                <div class="row">
                                    <div class="col-md-2">
                                        <h6 class="text-uppercase">Women's</h6>
                                        <ul class="nav flex-column">
                                            {% for w in women %}
                                            <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' w.pk %}">{{w.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <h6 class="text-uppercase">Men's</h6>
                                        <ul class="nav flex-column">
                                            {% for m in men %}
                                            <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' m.pk %}">{{m.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <h6 class="text-uppercase">Girl's</h6>
                                        <ul class="nav flex-column">
                                            {% for g in girls %}
                                            <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' g.pk %}">{{g.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-md-2">
                                        <h6 class="text-uppercase">Boy's</h6>
                                        <ul class="nav flex-column">
                                            {% for b in boys %}
                                            <li class="nav-item"><a class="nav-link" href="{% url 'shop:ProductDetail' b.pk %}">{{b.name}}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-md-4">
                                        <h6 class="text-uppercase">Featured Items</h6>
                                        <div class="row">
                                            {% for f in featured_product %}
                                            <div class="col-6 text-center">
                                                <a href="item.html">
                                                    <img src="{% for img in f.images.all|slice:1 %} {{img.image.url}} {% endfor %}" alt=""
                                                        class="img-fluid mt-2 mb-3"></a>
                                                <h6 class="mb-0"><a href="{% url 'shop:ProductDetail' f.pk %}">{{ f.name }}</a></h6>
                                                <p><span class="emphasis">${{ f.price }}</span></p>
                                                <a href="{% url 'shop:ProductDetail' f.pk %}" class="btn btn-sm btn-outline-secondary mt-0">Buy Now</a>
                                                <p>
                                            </div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'shop:about' %}">AboutUs</a></li>

                    {% if user.is_authenticated %}
                    {% url 'shop:cart' as cart_url %} <!--User in cart page Dont see cart in header -->
                    {% if not request.path == cart_url %} <!--User in cart page Dont see cart in header -->
                    <!--Shop cart item-->
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                            role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
                                class="fas fa-shopping-cart"></i> <span
                                class="badge badge-pill badge-primary">{{headercart.item_list.count}}</span></a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-cart" aria-labelledby="navbarDropdown">
                            <h6>{{headercart.item_list.count}}&nbsp;Items&nbsp;<span class="emphasis">${{headercart.cart_total}}</span></h6>
                            <div class="dropdown-divider"></div>
                            <ul class="shopping-cart-items">
                                {% for c in headercart.item_list.all %}
                                <li class="row">
                                    <div class="col-3">
                                        <img src="{% for img in c.item.product.images.all|slice:1 %} {{img.image.url}} {% endfor %}" width="60">
                                    </div>
                                    <div class="col-9">
                                        <h6><a href="{% url 'shop:ProductDetail' c.item.product.pk %}">{{c.item.product.name}}</a></h6>
                                        <span class="text-muted">{{c.order_num}}x</span>
                                        <span class="emphasis">${{c.item_total}}</span>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>

                            <a href="{% url 'shop:cart' %}" class="btn btn-lg btn-full-width btn-primary" style="margin: 0;">View Cart</a>
                        </div>
                    </li>
                    <!--Shop cart item-->
                    {% endif %} <!--User in cart page Dont see cart in header -->

                    <li class="nav-item"><a class="nav-link" href="{% url 'user:logout' %}">Logout</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:profile' %}">Profile</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'user:register' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</section>

aurum/media/templates/partials/paginat2.html
{% if is_paginated %}
<div class="container">
    <div class="row justify-content-center">
        <nav aria-label="page navigation">
            <ul class="pagination">

                <!-- Go page 1 with << -->
                <li class="page-item">
                    <a href="{{request.path}}?{{ request.GET.urlencode }}&page=1" class="page-link"><span>&laquo;</span></a>
                </li>

                <!-- Go 1 page previous with < -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="{{request.path}}?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}"
                        class="page-link"><span>&lt;</span></a>
                </li>
                {% endif %}

                <!-- Go 2 page previous with ... -->
                {% if page_obj.number|add:'-2' > 1 %}
                <li class="page-item">
                    <a href="{{request.path}}?{{ request.GET.urlencode }}&page={{ page_obj.number|add:'-3' }}" class="page-link"><span>&hellip;</span></a>
                </li>
                {% endif %}
                
                <!-- Display 3 page previous and 3 page next -->
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link">{{i}}</a>
                        </li>
                    {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a href="{{request.path}}?{{ request.GET.urlencode }}&page={{ i }}" class="page-link">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <!-- Go 2 page next with ... -->
                {% if page_obj.paginator.num_pages > page_obj.number|add:'2' %}
                <li class="page-item">
                    <a href="{{request.path}}?{{ request.GET.urlencode }}&page={{ page_obj.number|add:'3' }}" class="page-link"><span>&hellip;</span></a>
                </li>
                {% endif %}

                <!-- Go 1 page next with > -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="{{request.path}}?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}"
                        class=" page-link"><span>&gt;</span></a>
                </li>
                {% endif %}

                <!-- Go last page with >> -->
                <li class="page-item">
                    <a href="{{request.path}}?{{ request.GET.urlencode }}&page={{ paginator.num_pages }}" class="page-link"><span>&raquo;</span></a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endif %}