aurum/aurum/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("shop.urls")),
    path('user/',include("user.urls"))
]

aurum/shop/urls.py
from django.urls import path , re_path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'
urlpatterns = [
    path('' , views.index , name="index"),
    path('about/' , views.about , name="about"),
    path('cart/' , views.cart , name="cart"),
    path('del_cart_item/' , views.del_cart_item , name="delcartitem"),
    path('calcu_cart_item/' , views.calcu_cart_item , name="calcucartitem"),
    path('catalog/' , views.ProductListView.as_view(), name="catalog"),
    path('payment/' , views.payment, name="payment"),
    path('factor/' , views.factor, name="factor"),
    path('like_dislike/' , views.like_dislike, name="like_dislike"),
    re_path(r'^detail/(?P<pk>\d+)/$',views.ProductDetailView.as_view(), name='ProductDetail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aurum/user/urls.py
from django.urls import path , re_path
from user import views as user_views
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    path('register/' , user_views.register , name='register'),
    path('profile/' , user_views.profile , name='profile'), 
    path('login/' , auth_views.LoginView.as_view(template_name='user/login.html') , name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

aurum/shop/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from PIL import Image as PilImage

class Company(models.Model):
    email     = models.CharField(max_length=100 , blank=True, null=True, help_text="Enter Email for Contact us")
    phone     = models.CharField(max_length=100 , blank=True, null=True, help_text="Enter phone for Contact us")
    address   = models.CharField(max_length=100 , blank=True, null=True, help_text="Enter address for Contact us")
    instagram = models.CharField(max_length=100 ,default="#" , blank=True, null=True, help_text="Enter instagram link for Contact us")
    facebook  = models.CharField(max_length=100 ,default="#" , blank=True, null=True, help_text="Enter facebook link for Contact us")
    telegram  = models.CharField(max_length=100 ,default="#" , blank=True, null=True, help_text="Enter telegram link for Contact us")
    twitter   = models.CharField(max_length=100 ,default="#" , blank=True, null=True, help_text="Enter twitter for Contact us")
    images = models.ManyToManyField('Image')
    
    def __str__(self):
        return "Arum site EMAIL is {}".format(self.email)


class Category(models.Model):
    name = models.CharField(max_length=100 , help_text="Enter a Product Category...")

    def __str__(self):
        return "Category : {}".format(self.name)

class Image(models.Model):
    image = models.ImageField(default='default.jpg',upload_to='product_images')

    def save(self, *args, **kwargs):
        super().save(*args , **kwargs)

        img = PilImage.open(self.image.path)
        
        if img.height > 300 or img.width > 300 :
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class Product(models.Model):
    
    STATUS_CHOICES = (
        ('available' , 'Available'),
        ('not_available' , 'Not Available')
    )
    SEX_CHOICES = (
        ('men' , "Men`s"),
        ('women' , "Women`s"),
        ('boy' , "Boy`s"),
        ('girl' , "Girl`s")
    )

    name = models.CharField(max_length=100 , help_text="Enter Product Name...")
    description = models.TextField(max_length=1000 , help_text="Enter a description for this product")
    price = models.CharField(max_length=100 ,help_text="Enter a PRICE for this product")
    brand = models.CharField(max_length=100 ,help_text="Enter a BRAND for this product")
    sold_nums = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add = True)
    status  = models.CharField(max_length = 60 , choices = STATUS_CHOICES , default = 'available')
    sex  = models.CharField(max_length = 60 , choices = SEX_CHOICES , default = 'men')
    category = models.ForeignKey('Category',on_delete=models.SET_NULL , null = True)
    images = models.ManyToManyField('Image')

    def __str__(self):
        return "Product name is {}".format( self.name )

    class Meta:
        ordering = ('-created',)


class ProductInstance(models.Model):
    id = models.UUIDField(primary_key = True , default = uuid.uuid4,
                            editable= False , help_text = "Unique ID for particular Product in whole Shop")
    product = models.ForeignKey('Product',on_delete=models.SET_NULL,null = True)
    size = models.CharField(max_length=50 ,help_text="Enter Size for this product")
    color = models.CharField(max_length=50 ,help_text="Enter Color for this product")
    num = models.IntegerField(help_text="Enter Avalible Number for this product")
    
    def __str__ (self) :
        return "{0} , ({1})".format(self.id , self.product.name)

class CartItem(models.Model):
    item = models.ForeignKey('ProductInstance',on_delete=models.SET_NULL,null = True)
    order_num = models.IntegerField(default=1)

    @property
    def item_total(self):
        return self.order_num * int(self.item.product.price)

    class Meta :
        ordering = ['item']

    def __str__ (self) :
        return "Name : {0} , Size : {1} , Color : {2} , Order Num : {3}".format(self.item.product.name , self.item.size , self.item.color , self.order_num)

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL , null = True)
    item_list = models.ManyToManyField(CartItem)
    updated = models.DateTimeField(auto_now = True)
    is_paid = models.BooleanField(default=False)
    total = models.IntegerField(default=0)

    @property
    def cart_total(self):
        sum = 0
        for c in self.item_list.all() :
            sum += c.item_total
        return sum

    def __str__ (self) :
        return "Cart for:{0}".format(self.user)
    
class Comment(models.Model):
    STATUS_CHOICES = (
        ('published' , 'Published '),
        ('waiting' , 'Waiting')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    text = models.TextField(max_length=1000)
    product = models.ForeignKey('Product',on_delete=models.CASCADE)
    status  = models.CharField(max_length = 60 , choices = STATUS_CHOICES , default = 'published')
    created = models.DateTimeField(auto_now_add = True)
    user_like=models.ManyToManyField(User,related_name="likes",blank=True)
    user_dislike=models.ManyToManyField(User,related_name="dislikes",blank=True)

aurum/shop/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('subject', 'text')
        #widgets = {'user': forms.HiddenInput() , 'product': forms.HiddenInput() }

aurum/shop/views.py
from django.shortcuts import render , redirect
from django.views import generic
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse , JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormMixin
from .forms import CommentForm
from django.views.decorators.csrf import csrf_protect
from .models import Company , Category , Product , ProductInstance  , Cart , CartItem , Comment

from functools import reduce
import operator

def index(request):
    featured_products = Product.objects.all().order_by('-sold_nums')[:4]
    
    context = {'featured_products' : featured_products}
    return render (request , 'shop/home.html' , context)

def about(request):
    context = {}
    return render (request , 'shop/about.html' , context)

class ProductDetailView(FormMixin , generic.DetailView):
    model = Product
    template_name = 'shop/item.html'
    form_class = CommentForm
    loadcomment = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related'] = Product.objects.filter( Q(sex__iexact = self.object.sex) , ~Q(id__exact = self.object.id) ,
                Q(name__icontains=self.object.name) | Q(brand__icontains = self.object.brand) | Q(category_id__exact = self.object.category_id) ).order_by('-created')[:4]
        context['comments'] = Comment.objects.filter( Q(product_id__exact = self.kwargs.get('pk')) , Q(status__exact = 'published') ).order_by('-created')[:self.loadcomment]
        context['form'] = CommentForm()
        return context

    def get_success_url(self):
        messages.success(self.request , f'Your Comment Submited')
        return reverse('shop:ProductDetail', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid()  :
            return self.form_valid(form)
        #else:
        #    return self.form_invalid(form)
        if self.request.POST.get('loadmorecomment') and self.request.is_ajax(): #load more comment
            mt = int (self.request.POST.get('loadmorecomment'))
            self.loadcomment = self.loadcomment + (mt * 5)
        if self.request.POST.get('deletecomment') and self.request.is_ajax(): #delete comment
            pk = self.request.POST.get('pk')
            Comment.objects.filter(id=pk , user=request.user).delete()
        return super(ProductDetailView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user ##!!!!!
        form.instance.product = self.object    ##!!!!!
        form.save()
        return super(ProductDetailView, self).form_valid(form)

#for like or dislike a commnet
def like_dislike(request): 
    user = request.user
    if request.method=='POST' and request.is_ajax() :
        comment = Comment.objects.get(id = request.POST.get('pk'))
        if request.POST.get('like'): #delete from dislike and add to likes
            if comment.user_dislike.filter(id=user.id).exists():
                comment.user_dislike.remove(user)
            if not comment.user_like.filter(id=user.id):
                comment.user_like.add(user)

        elif request.POST.get('dislike'): #delete from like and add to dislikes
            if comment.user_like.filter(id=user.id).exists():
                comment.user_like.remove(user)
            if not comment.user_dislike.filter(id=user.id):
                comment.user_dislike.add(user)
            
        #return like number and dislike number with JSON    
        return JsonResponse({'liked':comment.user_like.count() , 'disliked':comment.user_dislike.count()})

class ProductListView(generic.ListView):
    model = Product
    context_object_name = 'Products'
    template_name = 'shop/catalog.html'
    #queryset = Book.objects.filter(title__icontains = 'hitler')[:5]

    #ordering = ['-created']

    ''' def get(self, request, *args, **kwargs):
        if (self.request.GET.get('pgnum')):
            self.paginate_by = self.request.GET.get('pgnum')
        return super(ProductListView, self).get(request, *args, **kwargs) '''

    def get(self, request, *args, **kwargs): 
        ######################################## FOR FILTER ###########################################
        if (self.request.GET.get('size')) or (self.request.GET.get('gender')) or (self.request.GET.get('category')):
            #All is str
            gender = self.request.GET.get('gender')
            size = self.request.GET.get('size')
            category = self.request.GET.get('category')
            
            category_args = []
            size_args = []

            if(gender  == ""):
                a = Q()
            else :
                a = Q(sex__iexact = gender)      
            
            if (category != ""):
                sp = [x.strip() for x in category.split(',')]
                for cat in sp :
                    category_args.append(Q(category__id = cat))

            if (size != ""):
                zp = [x.strip() for x in size.split(',')]
                for size_item in zp :
                    size_args.append(Q(productinstance__size = size_item))

            self.queryset = Product.objects.filter(a , reduce(operator.or_, category_args ,Q()) ,
                                                        reduce(operator.or_, size_args ,Q()) ).distinct() #Q() for initial !
            
            self.paginate_by = 3

        ######################################## FOR Sorting ###########################################
        if (self.request.GET.get('sortby')):
            self.ordering = [self.request.GET.get('sortby')]
        ############################### FOR Nums Product in one Page ##################################
        if (self.request.GET.get('pgnum')):
            self.paginate_by = self.request.GET.get('pgnum')



        return super(ProductListView, self).get(request, *args, **kwargs)


    paginate_by = 3

    #def get_queryset(self):
        #return Book.objects.filter(title__icontains='hitler')[:5]

    def get_context_data(self , **kwargs):
        context = super(ProductListView , self).get_context_data(**kwargs)
        context['categorys'] = Category.objects.all()
        context['sizes'] = ProductInstance.objects.order_by('size').values('size').distinct()
        context['sexs'] = Product.objects.order_by('sex').distinct('sex')
        context['max_price_product'] = Product.objects.order_by('price').first()
        return context

@login_required
def cart(request):
    #add to cart
    if request.method == "POST" and request.POST.get('formchoice') == 'formchoice' : # and re..
        if request.user.is_authenticated :
            # 1.select productinstance and add to CartItem
            choice = request.POST.get('choice')
            slt = choice.split("#") 

            pro = ProductInstance.objects.get(product_id = request.POST.get('product') , size__iexact = slt[0] , color__iexact = slt[1])
            cartitem = CartItem.objects.create(item = pro , order_num=1)
            # 2.Create or select Cart For currentuser
            cart, created = Cart.objects.get_or_create(user=request.user , is_paid=False)
            # 3.Add cartitem to cart
            cart.item_list.add(cartitem)
        else :
            messages.success(request , f'You Are Not Login !')
            return redirect('shop:catalog')  #go here      
    else :
        try :
            cart = Cart.objects.get(user=request.user , is_paid=False)
        except Cart.DoesNotExist :
            cart = None

    context = {'cart':cart}
    return render (request , 'shop/cart.html' , context)

@login_required
def del_cart_item(request):
    if request.method=="POST" and request.is_ajax():
        id = request.POST.get("cartitemid")
        try :
            cart = Cart.objects.get(user=request.user , is_paid=False)
        except Cart.DoesNotExist:                                                                                                       
            messages.error(request, f'No Cart For Delete')                                                                                                       
            return redirect('shop:index')
                    
        cart.item_list.filter(id=id).delete()
        #return HttpResponse("Item deleted !")
        return redirect('shop:cart')
@login_required
def calcu_cart_item(request):
    if request.method=="POST" and request.is_ajax():
        id = request.POST.get("cartitemid")
        new_order_num = int(request.POST.get("new_order_num"))
        try :
            cart = Cart.objects.get(user=request.user , is_paid=False)
        except Cart.DoesNotExist:                                                                                                       
            messages.error(request, f'No Cart For Edit')                                                                                                       
            return redirect('shop:index')
                    
        cart.item_list.filter(id=id).update(order_num = new_order_num)
        #return HttpResponse("Item deleted !")
        return redirect('shop:cart')

@login_required
def payment(request):
    context = {}
    return render (request , 'shop/payment.html' , context)

@login_required
def factor(request):
    try :
        cart = Cart.objects.get(user=request.user , is_paid=False)
    except Cart.DoesNotExist:
        messages.error(request, f'No Cart For Buy')                                                                                                       
        return redirect('shop:index')
    
    for c in cart.item_list.all():
        c.item.num = c.item.num - c.order_num #az mojodi kam kon
        c.item.save()
        c.item.product.sold_nums += c.order_num #be tedad foroukhteh shodeha azafe kon

aurum/media/templates/shop/cart.html
{% extends 'shared/site.html' %}
{% load static %}
{% block title %} Cart {% endblock title %}

{% block head %} <script src="{% static 'js/cart.js' %}"></script> {% endblock head %}
{% block body %}
        <section id="cartsection" class="cart text-center">
            {% if cart.item_list.count > 0 %}
            <div id="cart" class="container">
                <div  class="row">
                    <div class="col-12 text-center">
                        <h2 class="mb-3">Your Shopping Cart</h2>
                        
                        <div class="row justify-content-center">
                            <div class="alert alert-dismissible fade col-8" role="alert">
                            </div>
                        </div>
                        
                        <table  class="table table-condensed">
                            <thead>
                                <tr>
                                    <th style="width:60%">Product</th>
                                    <th style="width:12%">Price</th>
                                    <th style="width:10%">Quantity</th>
                                    <th style="width:16%"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for c in cart.item_list.all %}
                                <tr>
                                    <td data-th="Product">
                                        <div class="row">
                                            <div class="col-md-3 text-left">
                                                <img src="{% for img in c.item.product.images.all|slice:1 %} {{img.image.url}} {% endfor %}" alt="" class="img-fluid">
                                            </div>
                                            <div class="col-md-9 text-left mt-sm-2">
                                                <h4>{{c.item.product.name}}<p class="outnumber" style="color: tomato;">{% if c.order_num > c.item.num %}Sorry, Not available with this number 
                                                                            <script type="text/javascript">$("#checkout").addClass('disabled'); </script> {% endif %}</p></h4>
                                                <p>{{c.item.product.brand}}</p>
                                                <p class="text-muted">
                                                    <small>Color&nbsp;:&nbsp;{{c.item.color}} &nbsp;&&nbsp; Size&nbsp;:&nbsp;{{c.item.size}}</small>
                                                </p>
                                            </div>
                                        </div>
                                    </td>
                                    <td data-th="Price">${{c.item_total}}</td>
                                    <td data-th="Quantity">
                                        <input idincart="{{c.id}}" type="number" class="quantity form-control text-center" min="1" value="{{c.order_num}}">
                                    </td>
                                    <td class="actions" data-th="">
                                        <div class="text-right">
                                            <!-- <button idincart="{{c.id}}" class="calcu btn btn-white btn-md mb-2"><i class="fas fa-sync"></i></button> -->
                                            <button idincart="{{c.id}}" class="del btn btn-white btn-md mb-2"><i class="fas fa-trash"></i></button>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="divider"></div>
                        <div class="mb-5">
                            <h3>Subtotal:</h3>
                            <h1 id="cart_total" class="font-weight-bold">${{cart.cart_total}}</h1>
                            <p>(Excluding Delivery)</p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 mb-3 mb-m-1 text-md-left"><a href="{% url 'shop:catalog' %}"><i class="fas fa-arrow-left mr-2"></i>
                            Continue Shopping</a></div>
                    <div class="col-sm-6 text-md-right"><a href="{% url 'shop:payment' %}" id="checkout"
                            class="btn btn-primary btn-lg pl-5 pr-5">Checkout</a></div>
                </div>
            </div>
            {% else %}
            <div id="cart" class="container"> <!--id is same with UP because for replace when cart is empty with AJAX-->
                <div class="row justify-content-center">
                    <div class="col-12 col-md-8">
                        <h1>Your Cart IS Empty</h1><br><br>
                        <a href="{% url 'shop:catalog' %}" class="btn btn-primary btn">Go to Catalog Page</a>
                    </div>
                </div>
            </div>
            {% endif %}
        </section>
{% endblock body %}

aurum/media/templates/shop/item.html
{% extends 'shared/site.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Item {% endblock title %}
{% block head %}<script src="{% static 'js/item.js' %}"></script> {% endblock head %}
{% block body %}

		<section class="featured-block text-center">
			<div class="container">
				<div class="row">
					<div class="col-md-6 text-center">
						<div class="product-image mt-3">
							<img class="mainimage img-fluid" src="">
						</div>
						<div class="product-thumbnails">
							{% for img in product.images.all|slice:5 %}
							<a href="#">
								<img class="subimage mt-2 mr-2 img-fluid" src="{{img.image.url}}" >
							</a>
							{% endfor %}
							<!--
							<a href="#">
								<img class="mt-2 mr-2 img-fluid" src="images/placeholder-product.jpg" ></a>
							<a href="#">
								<img class="mt-2 mr-2 img-fluid" src="images/placeholder-product.jpg" ></a>
							<a href="#">
								<img class="mt-2 mr-2 img-fluid" src="images/placeholder-product.jpg" ></a>
							<a href="#">
							<img class="mt-2 mr-2 img-fluid" src="images/placeholder-product.jpg" ></a>
							-->
						</div>
					</div>
					<div class="col-md-6 mt-5 mt-md-2 text-center text-md-left">
						<h2 class="mb-3 mt-0">{{ product.name }}</h2>
						<p class="lead mt-2 mb-3 primary-color">${{ product.price }}</p>
						<h5 class="mt-1">Brand</h5>
						<p>{{ product.brand }}</p>
						<h5 class="mt-4">Description</h5>
						<p>{{ product.description }}</p>

						<form action="{% url 'shop:cart' %}" method="POST">
							{% csrf_token %}
								<select name="choice" id="myselect" class="custom-select form-control mt-4 mb-4">
									<option selected disabled>Size</option>
									{% for inst in product.productinstance_set.all %}
										{% if inst.num > 0 %}
											<option value="{{inst.size}}#{{inst.color}}">{{ inst.color }} (size : {{inst.size}} )</option>
										{% endif %}
									{% endfor %}
								</select>
							<input type="hidden" class="form-control quantity mb-4" name="product" value="{{product.id}}">
							<input type="hidden" class="form-control quantity mb-4" name="formchoice" value="formchoice">
							<!--Quantity: <input type="text" class="form-control quantity mb-4" name="" value="1">-->
							<button id="addtocart" type="submit" disabled class="btn btn-full-width btn-lg btn-outline-primary">Add to cart</button>
						
						</form>
					
					</div>

				</div>
				<div class="mt-5 divider"></div>
				{% if messages %}
					{% for message in messages %}
						<div class="col-12">
							{% if message.tags == "error" %}
								<div class="text-center alert alert-dismissible alert-danger fade show" role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
									{{message}}
								</div>
							{% else %}
								<div class="text-center alert alert-dismissible alert-{{message.tags}} fade show" role="alert">
									<button type="button" class="close" data-dismiss="alert" aria-label="Close">
									<span aria-hidden="true">&times;</span>
									</button>
									{{message}}
								</div>
							{% endif %} 
						</div>
					{% endfor %}
				{% endif %}

				{% if user.is_authenticated %}
				<div class="row">
					<div class="col-12">
						<div class="card shadow bg-light">
							<div class="card-body text-left">
								<legend>Add Your Comment</legend><br>
								<form method="POST" class="post-form">
									{% csrf_token %}
									<fieldset class="form-group">
										{{ form|crispy }}
									</fieldset>
									<fieldset class="form-group text-right">
										<button type="submit" class="btn btn-lg btn-primary">Send</button>
									</fieldset>
								</form>
							</div>
						</div>
					</div>
				</div>
				{% else %}
				<div class="row">
					<div class="col-12">
						<div class="card shadow bg-light">
							<div class="card-body">
								<legend>You must be logged in to post a comment</legend>
								<a href="{% url 'user:login' %}" class="btn btn-primary">Login</a>
							</div>
						</div>
					</div>
				</div>
				{% endif %}
				
				<div class="mt-5 divider"></div>

				<div id="commentsection">
					{% if comments %}
					<div class="row text-left mt-5">
						<div class="col-12">
							{% for cmt in comments %}
								<div class="card shadow bg-light mb-5">
									<div class="card-header bg-primary text-white">
										{{cmt.user}} : {{cmt.subject}}
										<div style="float:right;">
											{% if cmt.user == user %}
											<button pk={{cmt.pk}} class="del-comment btn btn-primary"><i class="fas fa-trash"></i></button>
											{% else %}
											<button pk={{cmt.pk}} class="like {% if user in cmt.user_like.all %} thumbs-green {% endif %} btn btn-primary"><i class="fas fa-thumbs-up"></i></button>
											<span liked-pk={{cmt.pk}}>{{cmt.user_like.count}}</span>
											<button pk={{cmt.pk}} class="dislike {% if user in cmt.user_dislike.all %} thumbs-red {% endif %} btn btn-primary"><i class="fas fa-thumbs-down"></i></button>
											<span disliked-pk={{cmt.pk}}>{{cmt.user_dislike.count}}</span>
											{% endif %}
										</div>
									</div>
									<div class="card-body">
										<blockquote class="blockquote mb-0">
											<p>{{cmt.text}}</p>
										</blockquote>
									</div>
									<div class="card-footer small text-right text-muted">{{cmt.created|timesince}} ago</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="row justify-content-center">
					<div class="col-4">
						<button pk={{product.pk}} count="1" id="loadmorebtn" class="btn btn-primary btn-lg btn-block">Load more</button>
					</div>
				</div>
				{% else %}
					<h4 class="mt-5">No Comments here yet</h4>
				{% endif %}
				</div>
			</div>
		</section>
		
		<div class="divider"></div>
		
		<section class="products text-center">
			<div class="container">
				<h3 class="mb-4">Related Products</h3>
				<div class="row">
					{% for related_obj in related %}
					<div class="col-sm-6 col-md-3 col-product">
						<figure>
							<img class="rounded-corners img-fluid" src="{% for img in related_obj.images.all|slice:1 %} {{img.image.url}} {% endfor %}"	width="240" height="240">
							<figcaption>
								<div class="thumb-overlay"><a href="{% url 'shop:ProductDetail' related_obj.pk %}" title="More Info">
									<i class="fas fa-search-plus"></i>
								</a></div>
							</figcaption>
						</figure>
						<h4><a href="{% url 'shop:ProductDetail' related_obj.pk %}">{{related_obj.name}}</a></h4>
						<p><span class="emphasis">${{related_obj.price}}</span></p>
					</div>
					{% endfor %}
				</div>
			</div>
		</section>
		
		<div class="divider"></div>
		
		<section class="cta text-center">
			<div class="container">
				<h3 class="mt-0 mb-4">Keep up with the latest discounts</h3>
				<form class="subscribe">
					<div class="form-group row pt-3">
						<div class="col-sm-8 mb-3">
							<input type="text" class="form-control" id="inputName" placeholder="Your Email">
						</div>
						<div class="col-sm-4">
							<button type="submit" class="btn btn-lg btn-outline-primary">Sign me up</button>
						</div>
					</div>
				</form>
			</div>
		</section>
{% endblock body %}

aurum/media/templates/shop/payment.html
{% extends 'shared/site.html' %}
{% load static %}
{% block title %} Payment (bank payment page) {% endblock title %}

{% block body %}
<div class="container pb-5">
    <div class="row text-center justify-content-center">
        <h1 class="col-12 mt-5">This is example for payment page </h1>
        <h4 class="col-12 mb-5">(replace with payment bank page)</h4>
        <a href="{% url 'shop:factor' %}" class="col-6 mt-5 btn btn-lg btn-success">Pay...</a>
    </div>
</div>
{% endblock body %}